# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: All OK Test

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: latest
        cache: 'npm'

    - name: Build app
      run: |
        npm ci
        npm install electron-builder --save-dev
        npm run buildMac --if-present

    - name: Prepare environment for tests
      run: |
        bash ./test/tools/prepareEnv.bash 

    - name: Run jest tests
      run: |
        npm run jest

    - name: Run webdriverIO tests
      run: |
        npm run wdio


